"""PDF generation service using ReportLab."""

import io
from datetime import datetime
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
    Image,
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT


class PDFGenerator:
    """Generate professional PDF documents."""

    def __init__(self, page_size: tuple = letter):
        self.page_size = page_size
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()

    def _setup_custom_styles(self) -> None:
        """Setup custom paragraph styles."""
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            spaceAfter=30,
            alignment=TA_CENTER,
            textColor=colors.HexColor('#1a365d'),
        ))
        self.styles.add(ParagraphStyle(
            name='CustomSubtitle',
            parent=self.styles['Normal'],
            fontSize=12,
            spaceAfter=20,
            alignment=TA_CENTER,
            textColor=colors.HexColor('#4a5568'),
        ))
        self.styles.add(ParagraphStyle(
            name='SectionHeader',
            parent=self.styles['Heading2'],
            fontSize=16,
            spaceBefore=20,
            spaceAfter=10,
            textColor=colors.HexColor('#2d3748'),
        ))
        self.styles.add(ParagraphStyle(
            name='CustomBody',
            parent=self.styles['Normal'],
            fontSize=10,
            spaceAfter=8,
            leading=14,
        ))
        self.styles.add(ParagraphStyle(
            name='Footer',
            parent=self.styles['Normal'],
            fontSize=8,
            textColor=colors.HexColor('#718096'),
            alignment=TA_CENTER,
        ))

    def _add_header_footer(self, canvas, doc) -> None:
        """Add header and footer to each page."""
        canvas.saveState()

        # Footer
        canvas.setFont('Helvetica', 8)
        canvas.setFillColor(colors.HexColor('#718096'))
        footer_text = f"Generated by Pasteur on {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}"
        canvas.drawCentredString(
            self.page_size[0] / 2,
            0.5 * inch,
            footer_text
        )

        # Page number
        page_num = f"Page {doc.page}"
        canvas.drawRightString(
            self.page_size[0] - 0.5 * inch,
            0.5 * inch,
            page_num
        )

        canvas.restoreState()

    def generate_project_pdf(
        self,
        project_name: str,
        project_status: str,
        project_description: str | None,
        tasks: list[dict[str, Any]],
        documents: list[dict[str, Any]],
    ) -> io.BytesIO:
        """Generate a PDF export for a project."""
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=self.page_size,
            rightMargin=0.75 * inch,
            leftMargin=0.75 * inch,
            topMargin=1 * inch,
            bottomMargin=1 * inch,
        )

        story = []

        # Title
        story.append(Paragraph(f"Project Export: {project_name}", self.styles['CustomTitle']))
        story.append(Paragraph(
            f"Status: {project_status} | Generated: {datetime.utcnow().strftime('%Y-%m-%d')}",
            self.styles['CustomSubtitle']
        ))
        story.append(Spacer(1, 20))

        # Description
        if project_description:
            story.append(Paragraph("Description", self.styles['SectionHeader']))
            story.append(Paragraph(project_description, self.styles['CustomBody']))
            story.append(Spacer(1, 15))

        # Tasks Section
        if tasks:
            story.append(Paragraph(f"Tasks ({len(tasks)})", self.styles['SectionHeader']))

            task_data = [['Title', 'Status', 'Priority', 'Due Date']]
            for task in tasks:
                task_data.append([
                    task.get('title', '')[:50],
                    task.get('status', 'N/A'),
                    task.get('priority', 'N/A'),
                    task.get('due_date', 'N/A'),
                ])

            task_table = Table(task_data, colWidths=[3*inch, 1*inch, 1*inch, 1.2*inch])
            task_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#e2e8f0')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor('#1a365d')),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 10),
                ('FONTSIZE', (0, 1), (-1, -1), 9),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('TOPPADDING', (0, 1), (-1, -1), 6),
                ('BOTTOMPADDING', (0, 1), (-1, -1), 6),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cbd5e0')),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f7fafc')]),
            ]))
            story.append(task_table)
            story.append(Spacer(1, 20))

        # Documents Section
        if documents:
            story.append(Paragraph(f"Documents ({len(documents)})", self.styles['SectionHeader']))

            doc_data = [['Title', 'Type', 'Created']]
            for doc_item in documents:
                doc_data.append([
                    doc_item.get('title', '')[:50],
                    doc_item.get('document_type', 'N/A'),
                    doc_item.get('created_at', 'N/A'),
                ])

            doc_table = Table(doc_data, colWidths=[4*inch, 1.2*inch, 1.5*inch])
            doc_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#e2e8f0')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor('#1a365d')),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 10),
                ('FONTSIZE', (0, 1), (-1, -1), 9),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('TOPPADDING', (0, 1), (-1, -1), 6),
                ('BOTTOMPADDING', (0, 1), (-1, -1), 6),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cbd5e0')),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f7fafc')]),
            ]))
            story.append(doc_table)

        doc.build(story, onFirstPage=self._add_header_footer, onLaterPages=self._add_header_footer)
        buffer.seek(0)
        return buffer

    def generate_tasks_pdf(
        self,
        tasks: list[dict[str, Any]],
        title: str = "Tasks Export",
    ) -> io.BytesIO:
        """Generate a PDF export for tasks."""
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=self.page_size,
            rightMargin=0.75 * inch,
            leftMargin=0.75 * inch,
            topMargin=1 * inch,
            bottomMargin=1 * inch,
        )

        story = []

        # Title
        story.append(Paragraph(title, self.styles['CustomTitle']))
        story.append(Paragraph(
            f"Total: {len(tasks)} tasks | Generated: {datetime.utcnow().strftime('%Y-%m-%d')}",
            self.styles['CustomSubtitle']
        ))
        story.append(Spacer(1, 20))

        # Summary by status
        status_counts: dict[str, int] = {}
        for task in tasks:
            status = task.get('status', 'unknown')
            status_counts[status] = status_counts.get(status, 0) + 1

        if status_counts:
            story.append(Paragraph("Summary by Status", self.styles['SectionHeader']))
            summary_data = [['Status', 'Count']]
            for status, count in sorted(status_counts.items()):
                summary_data.append([status.replace('_', ' ').title(), str(count)])

            summary_table = Table(summary_data, colWidths=[2*inch, 1*inch])
            summary_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#e2e8f0')),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('ALIGN', (1, 0), (1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cbd5e0')),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
                ('TOPPADDING', (0, 0), (-1, -1), 8),
            ]))
            story.append(summary_table)
            story.append(Spacer(1, 20))

        # Task list
        story.append(Paragraph("Task Details", self.styles['SectionHeader']))

        task_data = [['Title', 'Status', 'Priority', 'Due Date', 'Assignee']]
        for task in tasks:
            task_data.append([
                task.get('title', '')[:40],
                task.get('status', 'N/A'),
                task.get('priority', 'N/A'),
                task.get('due_date', 'N/A'),
                task.get('assignee', 'Unassigned')[:20],
            ])

        task_table = Table(task_data, colWidths=[2.5*inch, 0.9*inch, 0.8*inch, 1*inch, 1.3*inch])
        task_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#e2e8f0')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor('#1a365d')),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 9),
            ('FONTSIZE', (0, 1), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 10),
            ('TOPPADDING', (0, 1), (-1, -1), 5),
            ('BOTTOMPADDING', (0, 1), (-1, -1), 5),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cbd5e0')),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f7fafc')]),
        ]))
        story.append(task_table)

        doc.build(story, onFirstPage=self._add_header_footer, onLaterPages=self._add_header_footer)
        buffer.seek(0)
        return buffer

    def generate_document_pdf(
        self,
        title: str,
        content: str,
        metadata: dict[str, Any] | None = None,
    ) -> io.BytesIO:
        """Generate a PDF export for a single document."""
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=self.page_size,
            rightMargin=0.75 * inch,
            leftMargin=0.75 * inch,
            topMargin=1 * inch,
            bottomMargin=1 * inch,
        )

        story = []

        # Title
        story.append(Paragraph(title, self.styles['CustomTitle']))
        if metadata:
            meta_text = " | ".join([f"{k}: {v}" for k, v in metadata.items() if v])
            story.append(Paragraph(meta_text, self.styles['CustomSubtitle']))
        story.append(Spacer(1, 20))

        # Content - split by paragraphs
        if content:
            paragraphs = content.split('\n\n')
            for para in paragraphs:
                if para.strip():
                    # Handle markdown-style headers
                    if para.startswith('# '):
                        story.append(Paragraph(para[2:], self.styles['SectionHeader']))
                    elif para.startswith('## '):
                        story.append(Paragraph(para[3:], self.styles['Heading3']))
                    else:
                        story.append(Paragraph(para.replace('\n', '<br/>'), self.styles['CustomBody']))
                    story.append(Spacer(1, 8))

        doc.build(story, onFirstPage=self._add_header_footer, onLaterPages=self._add_header_footer)
        buffer.seek(0)
        return buffer

    def generate_ideas_pdf(
        self,
        ideas: list[dict[str, Any]],
        title: str = "Ideas Export",
    ) -> io.BytesIO:
        """Generate a PDF export for ideas."""
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=self.page_size,
            rightMargin=0.75 * inch,
            leftMargin=0.75 * inch,
            topMargin=1 * inch,
            bottomMargin=1 * inch,
        )

        story = []

        # Title
        story.append(Paragraph(title, self.styles['CustomTitle']))
        story.append(Paragraph(
            f"Total: {len(ideas)} ideas | Generated: {datetime.utcnow().strftime('%Y-%m-%d')}",
            self.styles['CustomSubtitle']
        ))
        story.append(Spacer(1, 20))

        # Ideas table
        idea_data = [['Title', 'Status', 'Priority', 'Type', 'Tags']]
        for idea in ideas:
            tags = ', '.join(idea.get('tags', []))[:30] if idea.get('tags') else ''
            idea_data.append([
                idea.get('title', '')[:35],
                idea.get('status', 'N/A'),
                idea.get('priority', 'N/A'),
                idea.get('idea_type', 'N/A'),
                tags,
            ])

        idea_table = Table(idea_data, colWidths=[2.2*inch, 0.9*inch, 0.8*inch, 0.9*inch, 1.7*inch])
        idea_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#e2e8f0')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor('#1a365d')),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 9),
            ('FONTSIZE', (0, 1), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 10),
            ('TOPPADDING', (0, 1), (-1, -1), 5),
            ('BOTTOMPADDING', (0, 1), (-1, -1), 5),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cbd5e0')),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f7fafc')]),
        ]))
        story.append(idea_table)

        doc.build(story, onFirstPage=self._add_header_footer, onLaterPages=self._add_header_footer)
        buffer.seek(0)
        return buffer

    def generate_analytics_pdf(
        self,
        metrics: dict[str, Any],
        title: str = "Analytics Report",
    ) -> io.BytesIO:
        """Generate a PDF export for analytics data."""
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=self.page_size,
            rightMargin=0.75 * inch,
            leftMargin=0.75 * inch,
            topMargin=1 * inch,
            bottomMargin=1 * inch,
        )

        story = []

        # Title
        story.append(Paragraph(title, self.styles['CustomTitle']))
        story.append(Paragraph(
            f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}",
            self.styles['CustomSubtitle']
        ))
        story.append(Spacer(1, 20))

        # Overview metrics
        story.append(Paragraph("Overview Metrics", self.styles['SectionHeader']))

        metrics_data = [['Metric', 'Value']]
        for key, value in metrics.items():
            if key != 'task_statuses':
                display_key = key.replace('_', ' ').title()
                metrics_data.append([display_key, str(value)])

        metrics_table = Table(metrics_data, colWidths=[3*inch, 2*inch])
        metrics_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#e2e8f0')),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('ALIGN', (1, 0), (1, -1), 'RIGHT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cbd5e0')),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f7fafc')]),
        ]))
        story.append(metrics_table)
        story.append(Spacer(1, 20))

        # Task status breakdown
        if 'task_statuses' in metrics:
            story.append(Paragraph("Task Status Breakdown", self.styles['SectionHeader']))

            status_data = [['Status', 'Count']]
            for status, count in metrics['task_statuses'].items():
                status_data.append([status.replace('_', ' ').title(), str(count)])

            status_table = Table(status_data, colWidths=[2*inch, 1*inch])
            status_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#e2e8f0')),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('ALIGN', (1, 0), (1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cbd5e0')),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
                ('TOPPADDING', (0, 0), (-1, -1), 8),
            ]))
            story.append(status_table)

        doc.build(story, onFirstPage=self._add_header_footer, onLaterPages=self._add_header_footer)
        buffer.seek(0)
        return buffer


# Singleton instance
pdf_generator = PDFGenerator()
